import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{
  children: React.ReactNode,
  analytics: React.ReactNode,
  team: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        RootLayout
        {props.children}
        {props.analytics}
        {props.team}
      </body>
    </html>
  );
}
